name: Release - Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # nécessaire pour publier sur ghcr.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract and normalize image name
      id: vars
      run: |
        VERSION=${GITHUB_REF##*/}
        REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/${REPO_LC}:${VERSION}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
